name: GeoNode Summit 2016
title: GeoNode Summit 2016
description: "Main website of GeoNode Summit 2016"
future: True
logo: "/assets/img/hiu_logo.png"
#markdown: redcarpet
timezone: America/New_York
permalink: none
# Local Dev
#baseurl:
#url: http://localhost:8000
#destination: _site
# GitHub Pages
#baseurl: /geonode-summit-2016
#url: http://geonode.org/geonode-summit-2016
#destination: _site
# Production
baseurl:
url: http://summit.geonode.org
destination: _site

# Explicit excludes, including dotfiles to be safe
exclude: [.DS_Store, .git, .gitignore, .vagrant, Gruntfile.js, Vagrantfile, package.json, node_modules, backups, _assets/img/src-images]

# Markdown Configuration
#redcarpet:
#  extensions: [with_toc_data]

# General
edit: true
code: "https://github.com/geonode/geonode-summit-2016"
branch: "gh-pages"
disclaimer: ""
privacy: ""
copyright: ""

# Analytics
ga:
  enabled: false
  code: "UA-XXXXXX-1"

# Twitter
twittercard:
  enabled: true
  site: "@GeoNode"

# Open Graph
opengraph:
  enabled: true

# Debugging & Testing
debug:
  monolith: true

# Dependencies Management
deps:
  angular:
    version: "1.4.0-beta.4"
  jquery:
    version: "1.11.3"

# Document & Media Storage
storage:
  bio_pics: "/assets/img/bios"


# GeoNode Summit
geonode_summit_2016:
  link:
    rsvp: https://docs.google.com/forms/d/e/1FAIpQLSdFdkHBVtbEEGMp2KuezujT7XZqr3Ig4JYyrHPskp9XGpeNEg/viewform
    gallery: http://geonode.org/gallery/
  featured:
    title: TBD
    image: "/assets/img/lightning-earth.png"
    description: TBD
  contacts:
    - name: Patrick Dufour
      email: pjdufour.dev@gmail.com
    - name: WFP Headquarters GIS Unit
      email: hq.gis@wfp.org
  sponsors:
    - image: /assets/img/logos/geonode_logo_white.png
      alt: GeoNode Logo
      link: http://geonode.org
    - image: /assets/img/logos/wfp_hq_gis_logo.png
      alt: WFP HQ GIS Logo
      link: http://wfp.org
  schedule:
    - id: monday
      title: Monday, November 28
      location: FAO
    - id: tuesday
      title: Tuesday, November 29
      location: FAO
    - id: wednesday
      title: Wednesday, November 30
      location: WFP
    - id: thursday
      title: Thursday, December 1
      location: FAO
    - id: friday
      title: Friday, December 2
      location: FAO
